ALTER TABLE users ADD COLUMN firstname TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN lastname TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN email TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN phone TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN s3_access_key TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN s3_secret_key TEXT NOT NULL DEFAULT '';
